### ISSUE TITLE
Dist folder pushed to repo

### ISSUE THREAD

**Issue by peterjgrainger** [speckleworks/SpeckleAdmin#111]
Step 0: 
- [x] I've  read the [contribution guidelines](https://github.com/speckleworks/SpeckleOrg/blob/master/CONTRIBUTING.md)!
#### Expected Behaviour
Dist folder is dynamically generated

#### Actual Behaviour
Dist folder is in source control

#### Affected Projects
n/a

#### Reproduction Steps & System Config (win, osx, web, etc.)
n/a
#### Proposed Solution (if any)

Remove Dist folder and contents

**Comment by didimitrie** [comment]
Hello @peterjgrainger! Sorry it took me a week to get to this. Long story short: 
- this is correct, and the way things should be! 
- unfortunately, the way things currently are, from a bug it became a "feature" 😢 
- we can't really fix it 🤦 

Basically, people started depending that when they `git clone` this repo they have a `/dist` folder already. I know it's horrible practice... but it's what we're stuck with in 1.0. The docker compose file is the main culprit here, it doesn't build admin, it just clones it (https://github.com/speckleworks/SpeckleServer/blob/master/Dockerfile#L13).

**Comment by peterjgrainger** [comment]
Was worried you were going to say that :)

We'll have to handle it our end. Thanks for looking anyway.
