### ISSUE TITLE
Zoom extents centres around the origin

### ISSUE THREAD

**Issue by didimitrie** [speckleworks/SpeckleAdmin#43]
Step 0: 
- [x] I've  read the [contribution guidelines](https://github.com/speckleworks/SpeckleOrg/blob/master/CONTRIBUTING.md)!

Zoom extents somehow still centres the scene with including the origin, as far as I understand. 

To reproduce, load a model with geometry far off from the origin and press `spacebar` to zoom extents.

**Comment by ggooskens** [comment]
Never knew a zoom extents existed! Awesome. Could there be a little tooltip for this?

**Comment by didimitrie** [comment]
> Never knew a zoom extents existed! Awesome. Could there be a little tooltip for this?

Before we get there, you can have an issue to have a little tooltip :D  https://github.com/speckleworks/SpeckleAdmin/issues/45
