### ISSUE TITLE
Button to access child stream from the history in the viewer redirects to a wrong URL

### ISSUE THREAD

**Issue by PaulPoinet** [speckleworks/SpeckleAdmin#50]
Step 0: 
- [x ] I've  read the [contribution guidelines](https://github.com/speckleworks/SpeckleOrg/blob/master/CONTRIBUTING.md)!
#### Expected Behaviour
Access child stream smoothly

#### Actual Behaviour
What's actually going on!
![image](https://user-images.githubusercontent.com/22736626/58954609-95846400-8791-11e9-9295-1e05aab81c41.png)

#### Affected Projects
@didimitrie to be checked, i dont know

#### Proposed Solution (if any)
replace `&` with `?` in the URL

**Comment by didimitrie** [comment]
That definitively looks like the *deprecated* [old viewer](https://github.com/speckleworks/SpeckleViewer). It's still there on hestia out of sentimental reasons more than anything else. 

Children are not exposed in the current admin-embedded viewer, but if that's a new feature request - closing this one off.
