### ISSUE TITLE
Doesn't allow me to make changes online

### ISSUE THREAD

**Issue by jamievincent** [speckleworks/SpeckleAdmin#55]
I'm getting the error "This stream is not marked as online editable." on the data tab in my stream. How cam I change this?

**Comment by didimitrie** [comment]
Hello @jamievincent, next time please use as much as relevant the issue template. This question would be more suited for [the forum](https://discourse.speckle.works) or the slack channel.

The data tab is currently available only for streams created online, please check this: https://speckle.systems/docs/basics/data-stream-creation
