### ISSUE TITLE
Some curves are dismissed by the viewer

### ISSUE THREAD

**Issue by PaulPoinet** [speckleworks/SpeckleAdmin#74]
Step 0: 
- [x] I've  read the [contribution guidelines](https://github.com/speckleworks/SpeckleOrg/blob/master/CONTRIBUTING.md)!
#### Expected Behaviour
The viewer should display all the curves present in the stream.

#### Actual Behaviour
The viewer shows less curves than it should :(

#### Reproduction Steps & System Config (win, osx, web, etc.)
Check this same stream on the API side and on the viewer side:
https://hestia.speckle.works/api/streams/GMmiyTy4z/
https://hestia.speckle.works/#/view/GMmiyTy4z
@didimitrie I gave you access
#### Proposed Solution (if any)
¯\_(ツ)_/¯

**Comment by didimitrie** [comment]
Hello @PaulPoinet , i think i got this. Just to confirm:

![image](https://user-images.githubusercontent.com/7696515/66058043-96f04e00-e531-11e9-8de5-9d90be9bb407.png)

- left - old 
- right - fixed

Does it look all right to you?

**Comment by PaulPoinet** [comment]
Yep, great! thanks

**Comment by PaulPoinet** [comment]
although I am not sure whether some should also be present in these locations:

![image](https://user-images.githubusercontent.com/22736626/66058623-986e4600-e532-11e9-90ef-efa9238b1c90.png)

Not sure whether it's a bug or I did not send the objects properly at the first place...

**Comment by didimitrie** [comment]
can you send me a stream that you defs know what the geometry should look like?

**Comment by PaulPoinet** [comment]
Just received the above stream in GH, appears to be the same as the fixed version. So it should be bug-free!
![image](https://user-images.githubusercontent.com/22736626/66060732-14b65880-e536-11e9-8f98-241160956c90.png)

**Comment by didimitrie** [comment]
Yes! 🍻
