### ISSUE TITLE
SpeckleViewer right side panel tabs are hidden 

### ISSUE THREAD

**Issue by tluth** [speckleworks/SpeckleAdmin#84]
Step 0: 
- [x] I've  read the [contribution guidelines](https://github.com/speckleworks/SpeckleOrg/blob/master/CONTRIBUTING.md)!
#### Expected Behaviour
In the right side panel there are 4 tabs across the top of the panel which allow you to toggle between 'search for streams', 'select property...', view code, and settings. These should always be accessible 

#### Actual Behaviour
When the page is zoomed to a certain extent, the right hand panel auto-hides and after this point, the tabs across the top of the panel are no longer visible. 

#### Affected Projects
nah

#### Reproduction Steps & System Config (win, osx, web, etc.)
- Open https://hestia.speckle.works/#/view in chrome
- zoom until the tool panel hides 
- open the panel again to see if the tabs are still visible

e.g. https://www.dropbox.com/s/py3xp9lxc9je6hv/twinner%20-%20Google%20Chrome%2021.10.2019%2013_42_36.mp4?dl=0

**Comment by didimitrie** [comment]
I can reproduce. It's annoying; I'll try and fix this next week.
