### ISSUE TITLE
login form shouldn't validate password length

### ISSUE THREAD

**Issue by radumg** [speckleworks/SpeckleAdmin#9]
## Actual behaviour
I've successfully created a Speckle account with the API :
```js
{
  "email": "radug@speckle.works",
  "password": "testing",
  "name": "Radu",
  "surname": "Gidei",
  "company": "Grimshaw",
}
```
 but if i try to log in to Speckle server using the Admin app, it validates the password field, requiring it to be longer than 8 characters.

![speckle login](https://user-images.githubusercontent.com/11439624/38449259-43a37102-3a04-11e8-8dd0-2398eb2712ae.PNG)

## Expected behaviour
I should be able to log in using my pre-existing password.
Whilst validation is expected on `registration` page, it shouldn't be on `login` page.

**Comment by mswaidan** [comment]
@didimitrie has done 100% of the admin so he should weigh in on this, but I think we want to validate the password. We want to enforce that passwords are at least 8 chars, so fix should be on the server side, rejecting short passwords.

**Comment by radumg** [comment]
i agree fix should be server-side, never seen password validated on login, it should accept anything the user inputs, including & especially wrong passwords 😬 

note this doesn't affect the registration tab, which keeps its password length validation.
